spring:
  application:
    name: user-managment
    
  banner:
   location: classpath:/banners/banner.txt       
server:
  port: 9095

# ===============================
# = SPRING DATABASE
# ===============================
datasource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  databaseUrl: jdbc:sqlserver://localhost:1433;DatabaseName=friend_finder;characterEncoding=UTF-8;encrypt=false
  databaseUser: root
  databasePassword: admin
  platform: hibernate.dialect.SQLServer2012Dialect

# ===============================
# = JPA / HIBERNATE
# ===============================
jpa:
  showSql: true
  hibernate:
    hibernateDDLAuto: create
    hibernateDialect: org.hibernate.dialect.SQLServer2012Dialect
    create_empty_composites:
      enabled: true