spring:
  application:
    name: user-managment
    
  banner:
   location: classpath:/banners/banner.txt       
server:
  port: 9095

# ===============================
# = SPRING DATABASE
# ===============================
datasource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  databaseUrl: jdbc:sqlserver://localhost;DatabaseName=ff_user_management;characterEncoding=UTF-8;encrypt=false
  databaseUser: root
  databasePassword: admin
  platform: org.hibernate.dialect.SQLServer2012Dialect

# ===============================
# = JPA / HIBERNATE
# ===============================
jpa:
  show-sql: true
  hibernate:
    generate-ddl: true
    hibernateDDlAuto: update
    hibernateDialect: org.hibernate.dialect.SQLServer2012Dialect
    
    